# Generated by Django 4.1.5 on 2023-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='book_pages',
            field=models.IntegerField(),
        ),
    ]
